name: duckov_mod_manager
description: "Escape from Duckov 模组管理器 - Windows专用版本"
publish_to: 'none'

version: 0.1.1+1

environment:
  sdk: ^3.11.0-114.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # 添加进程管理依赖
  process_run: ^0.12.0
  
  # 添加HTTP请求支持
  http: ^1.2.1
  
  # 添加URL启动支持
  url_launcher: ^6.1.0
  
  # 添加HTML解析支持
  html: ^0.15.4

  provider: ^6.1.1
  file_picker: ^5.0.1
  flutter_markdown: ^0.6.16+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  # 仅支持Windows平台
  generate: true

  uses-material-design: true

  # 添加自定义字体
  fonts:
    - family: MiSans
      fonts:
        - asset: lib/assets/fonts/MiSans-Regular.ttf
        - asset: lib/assets/fonts/MiSans-Regular.woff2
